// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/johnsonoklii/agentgo/apps/baseService/internal/biz/usecase/auth"
	"github.com/johnsonoklii/agentgo/apps/baseService/internal/biz/usecase/user"
	"github.com/johnsonoklii/agentgo/apps/baseService/internal/conf"
	"github.com/johnsonoklii/agentgo/apps/baseService/internal/data/db"
	"github.com/johnsonoklii/agentgo/apps/baseService/internal/server"
	"github.com/johnsonoklii/agentgo/apps/baseService/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, data *conf.Data, registry *conf.Registry, logger log.Logger) (*kratos.App, func(), error) {
	dbData, cleanup, err := db.NewData(data, logger)
	if err != nil {
		return nil, nil, err
	}
	userRepo := db.NewUserRepo(dbData, logger)
	userUsecase := user.NewUserUsecase(userRepo, logger)
	userService := service.NewUserService(userUsecase, logger)
	authUsecase := auth.NewAuthUsecase(userRepo, dbData, logger)
	authService := service.NewAuthService(authUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, userService, authService, logger)
	httpServer := server.NewHTTPServer(confServer, userService, authService, logger)
	registrar := server.NewRegistrar(registry)
	app := newApp(logger, confServer, grpcServer, httpServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
