// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.12.4
// source: agent_workspace/v1/agent_workspace.proto

package v1

import (
	v1 "github.com/johnsonoklii/agentgo/apps/agentService/api/agent/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 获取工作区Agent列表请求
type GetWorkspaceAgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspaceId,proto3" json:"workspaceId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkspaceAgentsRequest) Reset() {
	*x = GetWorkspaceAgentsRequest{}
	mi := &file_agent_workspace_v1_agent_workspace_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkspaceAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkspaceAgentsRequest) ProtoMessage() {}

func (x *GetWorkspaceAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_workspace_v1_agent_workspace_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkspaceAgentsRequest.ProtoReflect.Descriptor instead.
func (*GetWorkspaceAgentsRequest) Descriptor() ([]byte, []int) {
	return file_agent_workspace_v1_agent_workspace_proto_rawDescGZIP(), []int{0}
}

func (x *GetWorkspaceAgentsRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

// 获取工作区Agent列表响应
type GetWorkspaceAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*v1.AgentInfo        `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkspaceAgentsResponse) Reset() {
	*x = GetWorkspaceAgentsResponse{}
	mi := &file_agent_workspace_v1_agent_workspace_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkspaceAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkspaceAgentsResponse) ProtoMessage() {}

func (x *GetWorkspaceAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_workspace_v1_agent_workspace_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkspaceAgentsResponse.ProtoReflect.Descriptor instead.
func (*GetWorkspaceAgentsResponse) Descriptor() ([]byte, []int) {
	return file_agent_workspace_v1_agent_workspace_proto_rawDescGZIP(), []int{1}
}

func (x *GetWorkspaceAgentsResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetWorkspaceAgentsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetWorkspaceAgentsResponse) GetData() []*v1.AgentInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

// 添加Agent到工作区请求
type AddAgentToWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agentId,proto3" json:"agentId,omitempty"`
	WorkspaceId   string                 `protobuf:"bytes,2,opt,name=workspaceId,proto3" json:"workspaceId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAgentToWorkspaceRequest) Reset() {
	*x = AddAgentToWorkspaceRequest{}
	mi := &file_agent_workspace_v1_agent_workspace_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAgentToWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAgentToWorkspaceRequest) ProtoMessage() {}

func (x *AddAgentToWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_workspace_v1_agent_workspace_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAgentToWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*AddAgentToWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_agent_workspace_v1_agent_workspace_proto_rawDescGZIP(), []int{2}
}

func (x *AddAgentToWorkspaceRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AddAgentToWorkspaceRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

// 添加Agent到工作区响应
type AddAgentToWorkspaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAgentToWorkspaceResponse) Reset() {
	*x = AddAgentToWorkspaceResponse{}
	mi := &file_agent_workspace_v1_agent_workspace_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAgentToWorkspaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAgentToWorkspaceResponse) ProtoMessage() {}

func (x *AddAgentToWorkspaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_workspace_v1_agent_workspace_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAgentToWorkspaceResponse.ProtoReflect.Descriptor instead.
func (*AddAgentToWorkspaceResponse) Descriptor() ([]byte, []int) {
	return file_agent_workspace_v1_agent_workspace_proto_rawDescGZIP(), []int{3}
}

func (x *AddAgentToWorkspaceResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AddAgentToWorkspaceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 从工作区删除Agent请求
type RemoveAgentFromWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agentId,proto3" json:"agentId,omitempty"`
	WorkspaceId   string                 `protobuf:"bytes,2,opt,name=workspaceId,proto3" json:"workspaceId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveAgentFromWorkspaceRequest) Reset() {
	*x = RemoveAgentFromWorkspaceRequest{}
	mi := &file_agent_workspace_v1_agent_workspace_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveAgentFromWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAgentFromWorkspaceRequest) ProtoMessage() {}

func (x *RemoveAgentFromWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_workspace_v1_agent_workspace_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAgentFromWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*RemoveAgentFromWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_agent_workspace_v1_agent_workspace_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveAgentFromWorkspaceRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RemoveAgentFromWorkspaceRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

// 从工作区删除Agent响应
type RemoveAgentFromWorkspaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveAgentFromWorkspaceResponse) Reset() {
	*x = RemoveAgentFromWorkspaceResponse{}
	mi := &file_agent_workspace_v1_agent_workspace_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveAgentFromWorkspaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAgentFromWorkspaceResponse) ProtoMessage() {}

func (x *RemoveAgentFromWorkspaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_workspace_v1_agent_workspace_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAgentFromWorkspaceResponse.ProtoReflect.Descriptor instead.
func (*RemoveAgentFromWorkspaceResponse) Descriptor() ([]byte, []int) {
	return file_agent_workspace_v1_agent_workspace_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveAgentFromWorkspaceResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RemoveAgentFromWorkspaceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_agent_workspace_v1_agent_workspace_proto protoreflect.FileDescriptor

const file_agent_workspace_v1_agent_workspace_proto_rawDesc = "" +
	"\n" +
	"(agent_workspace/v1/agent_workspace.proto\x12\x16api.agent_workspace.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x14agent/v1/agent.proto\"=\n" +
	"\x19GetWorkspaceAgentsRequest\x12 \n" +
	"\vworkspaceId\x18\x01 \x01(\tR\vworkspaceId\"w\n" +
	"\x1aGetWorkspaceAgentsResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12+\n" +
	"\x04data\x18\x03 \x03(\v2\x17.api.agent.v1.AgentInfoR\x04data\"X\n" +
	"\x1aAddAgentToWorkspaceRequest\x12\x18\n" +
	"\aagentId\x18\x01 \x01(\tR\aagentId\x12 \n" +
	"\vworkspaceId\x18\x02 \x01(\tR\vworkspaceId\"K\n" +
	"\x1bAddAgentToWorkspaceResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"]\n" +
	"\x1fRemoveAgentFromWorkspaceRequest\x12\x18\n" +
	"\aagentId\x18\x01 \x01(\tR\aagentId\x12 \n" +
	"\vworkspaceId\x18\x02 \x01(\tR\vworkspaceId\"P\n" +
	" RemoveAgentFromWorkspaceResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x9e\x04\n" +
	"\x0eAgentWorkspace\x12\xa0\x01\n" +
	"\x12GetWorkspaceAgents\x121.api.agent_workspace.v1.GetWorkspaceAgentsRequest\x1a2.api.agent_workspace.v1.GetWorkspaceAgentsResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/v1/agent/workspaces/agents\x12\xa9\x01\n" +
	"\x13AddAgentToWorkspace\x122.api.agent_workspace.v1.AddAgentToWorkspaceRequest\x1a3.api.agent_workspace.v1.AddAgentToWorkspaceResponse\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/v1/agent/workspaces/{agentId}\x12\xbc\x01\n" +
	"\x18RemoveAgentFromWorkspace\x127.api.agent_workspace.v1.RemoveAgentFromWorkspaceRequest\x1a8.api.agent_workspace.v1.RemoveAgentFromWorkspaceResponse\"-\x82\xd3\xe4\x93\x02'*%/v1/agent/workspaces/agents/{agentId}BMZKgithub.com/johnsonoklii/agentgo/apps/agentService/api/agent_workspace/v1;v1b\x06proto3"

var (
	file_agent_workspace_v1_agent_workspace_proto_rawDescOnce sync.Once
	file_agent_workspace_v1_agent_workspace_proto_rawDescData []byte
)

func file_agent_workspace_v1_agent_workspace_proto_rawDescGZIP() []byte {
	file_agent_workspace_v1_agent_workspace_proto_rawDescOnce.Do(func() {
		file_agent_workspace_v1_agent_workspace_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_workspace_v1_agent_workspace_proto_rawDesc), len(file_agent_workspace_v1_agent_workspace_proto_rawDesc)))
	})
	return file_agent_workspace_v1_agent_workspace_proto_rawDescData
}

var file_agent_workspace_v1_agent_workspace_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_agent_workspace_v1_agent_workspace_proto_goTypes = []any{
	(*GetWorkspaceAgentsRequest)(nil),        // 0: api.agent_workspace.v1.GetWorkspaceAgentsRequest
	(*GetWorkspaceAgentsResponse)(nil),       // 1: api.agent_workspace.v1.GetWorkspaceAgentsResponse
	(*AddAgentToWorkspaceRequest)(nil),       // 2: api.agent_workspace.v1.AddAgentToWorkspaceRequest
	(*AddAgentToWorkspaceResponse)(nil),      // 3: api.agent_workspace.v1.AddAgentToWorkspaceResponse
	(*RemoveAgentFromWorkspaceRequest)(nil),  // 4: api.agent_workspace.v1.RemoveAgentFromWorkspaceRequest
	(*RemoveAgentFromWorkspaceResponse)(nil), // 5: api.agent_workspace.v1.RemoveAgentFromWorkspaceResponse
	(*v1.AgentInfo)(nil),                     // 6: api.agent.v1.AgentInfo
}
var file_agent_workspace_v1_agent_workspace_proto_depIdxs = []int32{
	6, // 0: api.agent_workspace.v1.GetWorkspaceAgentsResponse.data:type_name -> api.agent.v1.AgentInfo
	0, // 1: api.agent_workspace.v1.AgentWorkspace.GetWorkspaceAgents:input_type -> api.agent_workspace.v1.GetWorkspaceAgentsRequest
	2, // 2: api.agent_workspace.v1.AgentWorkspace.AddAgentToWorkspace:input_type -> api.agent_workspace.v1.AddAgentToWorkspaceRequest
	4, // 3: api.agent_workspace.v1.AgentWorkspace.RemoveAgentFromWorkspace:input_type -> api.agent_workspace.v1.RemoveAgentFromWorkspaceRequest
	1, // 4: api.agent_workspace.v1.AgentWorkspace.GetWorkspaceAgents:output_type -> api.agent_workspace.v1.GetWorkspaceAgentsResponse
	3, // 5: api.agent_workspace.v1.AgentWorkspace.AddAgentToWorkspace:output_type -> api.agent_workspace.v1.AddAgentToWorkspaceResponse
	5, // 6: api.agent_workspace.v1.AgentWorkspace.RemoveAgentFromWorkspace:output_type -> api.agent_workspace.v1.RemoveAgentFromWorkspaceResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_agent_workspace_v1_agent_workspace_proto_init() }
func file_agent_workspace_v1_agent_workspace_proto_init() {
	if File_agent_workspace_v1_agent_workspace_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_workspace_v1_agent_workspace_proto_rawDesc), len(file_agent_workspace_v1_agent_workspace_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_workspace_v1_agent_workspace_proto_goTypes,
		DependencyIndexes: file_agent_workspace_v1_agent_workspace_proto_depIdxs,
		MessageInfos:      file_agent_workspace_v1_agent_workspace_proto_msgTypes,
	}.Build()
	File_agent_workspace_v1_agent_workspace_proto = out.File
	file_agent_workspace_v1_agent_workspace_proto_goTypes = nil
	file_agent_workspace_v1_agent_workspace_proto_depIdxs = nil
}
