// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: agent_workspace/v1/agent_workspace.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentWorkspace_GetWorkspaceAgents_FullMethodName       = "/api.agent_workspace.v1.AgentWorkspace/GetWorkspaceAgents"
	AgentWorkspace_AddAgentToWorkspace_FullMethodName      = "/api.agent_workspace.v1.AgentWorkspace/AddAgentToWorkspace"
	AgentWorkspace_RemoveAgentFromWorkspace_FullMethodName = "/api.agent_workspace.v1.AgentWorkspace/RemoveAgentFromWorkspace"
)

// AgentWorkspaceClient is the client API for AgentWorkspace service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentWorkspaceClient interface {
	// 获取工作区下的Agent列表
	GetWorkspaceAgents(ctx context.Context, in *GetWorkspaceAgentsRequest, opts ...grpc.CallOption) (*GetWorkspaceAgentsResponse, error)
	// 添加Agent到工作区
	AddAgentToWorkspace(ctx context.Context, in *AddAgentToWorkspaceRequest, opts ...grpc.CallOption) (*AddAgentToWorkspaceResponse, error)
	// 删除工作区中的Agent
	RemoveAgentFromWorkspace(ctx context.Context, in *RemoveAgentFromWorkspaceRequest, opts ...grpc.CallOption) (*RemoveAgentFromWorkspaceResponse, error)
}

type agentWorkspaceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentWorkspaceClient(cc grpc.ClientConnInterface) AgentWorkspaceClient {
	return &agentWorkspaceClient{cc}
}

func (c *agentWorkspaceClient) GetWorkspaceAgents(ctx context.Context, in *GetWorkspaceAgentsRequest, opts ...grpc.CallOption) (*GetWorkspaceAgentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWorkspaceAgentsResponse)
	err := c.cc.Invoke(ctx, AgentWorkspace_GetWorkspaceAgents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentWorkspaceClient) AddAgentToWorkspace(ctx context.Context, in *AddAgentToWorkspaceRequest, opts ...grpc.CallOption) (*AddAgentToWorkspaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddAgentToWorkspaceResponse)
	err := c.cc.Invoke(ctx, AgentWorkspace_AddAgentToWorkspace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentWorkspaceClient) RemoveAgentFromWorkspace(ctx context.Context, in *RemoveAgentFromWorkspaceRequest, opts ...grpc.CallOption) (*RemoveAgentFromWorkspaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveAgentFromWorkspaceResponse)
	err := c.cc.Invoke(ctx, AgentWorkspace_RemoveAgentFromWorkspace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentWorkspaceServer is the server API for AgentWorkspace service.
// All implementations must embed UnimplementedAgentWorkspaceServer
// for forward compatibility.
type AgentWorkspaceServer interface {
	// 获取工作区下的Agent列表
	GetWorkspaceAgents(context.Context, *GetWorkspaceAgentsRequest) (*GetWorkspaceAgentsResponse, error)
	// 添加Agent到工作区
	AddAgentToWorkspace(context.Context, *AddAgentToWorkspaceRequest) (*AddAgentToWorkspaceResponse, error)
	// 删除工作区中的Agent
	RemoveAgentFromWorkspace(context.Context, *RemoveAgentFromWorkspaceRequest) (*RemoveAgentFromWorkspaceResponse, error)
	mustEmbedUnimplementedAgentWorkspaceServer()
}

// UnimplementedAgentWorkspaceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentWorkspaceServer struct{}

func (UnimplementedAgentWorkspaceServer) GetWorkspaceAgents(context.Context, *GetWorkspaceAgentsRequest) (*GetWorkspaceAgentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWorkspaceAgents not implemented")
}
func (UnimplementedAgentWorkspaceServer) AddAgentToWorkspace(context.Context, *AddAgentToWorkspaceRequest) (*AddAgentToWorkspaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddAgentToWorkspace not implemented")
}
func (UnimplementedAgentWorkspaceServer) RemoveAgentFromWorkspace(context.Context, *RemoveAgentFromWorkspaceRequest) (*RemoveAgentFromWorkspaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveAgentFromWorkspace not implemented")
}
func (UnimplementedAgentWorkspaceServer) mustEmbedUnimplementedAgentWorkspaceServer() {}
func (UnimplementedAgentWorkspaceServer) testEmbeddedByValue()                        {}

// UnsafeAgentWorkspaceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentWorkspaceServer will
// result in compilation errors.
type UnsafeAgentWorkspaceServer interface {
	mustEmbedUnimplementedAgentWorkspaceServer()
}

func RegisterAgentWorkspaceServer(s grpc.ServiceRegistrar, srv AgentWorkspaceServer) {
	// If the following call pancis, it indicates UnimplementedAgentWorkspaceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentWorkspace_ServiceDesc, srv)
}

func _AgentWorkspace_GetWorkspaceAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkspaceAgentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentWorkspaceServer).GetWorkspaceAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentWorkspace_GetWorkspaceAgents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentWorkspaceServer).GetWorkspaceAgents(ctx, req.(*GetWorkspaceAgentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentWorkspace_AddAgentToWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddAgentToWorkspaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentWorkspaceServer).AddAgentToWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentWorkspace_AddAgentToWorkspace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentWorkspaceServer).AddAgentToWorkspace(ctx, req.(*AddAgentToWorkspaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentWorkspace_RemoveAgentFromWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveAgentFromWorkspaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentWorkspaceServer).RemoveAgentFromWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentWorkspace_RemoveAgentFromWorkspace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentWorkspaceServer).RemoveAgentFromWorkspace(ctx, req.(*RemoveAgentFromWorkspaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentWorkspace_ServiceDesc is the grpc.ServiceDesc for AgentWorkspace service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentWorkspace_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.agent_workspace.v1.AgentWorkspace",
	HandlerType: (*AgentWorkspaceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetWorkspaceAgents",
			Handler:    _AgentWorkspace_GetWorkspaceAgents_Handler,
		},
		{
			MethodName: "AddAgentToWorkspace",
			Handler:    _AgentWorkspace_AddAgentToWorkspace_Handler,
		},
		{
			MethodName: "RemoveAgentFromWorkspace",
			Handler:    _AgentWorkspace_RemoveAgentFromWorkspace_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent_workspace/v1/agent_workspace.proto",
}
