// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/johnsonoklii/agentgo/apps/agentService/internal/biz/usecase/agent"
	"github.com/johnsonoklii/agentgo/apps/agentService/internal/conf"
	"github.com/johnsonoklii/agentgo/apps/agentService/internal/data/db"
	"github.com/johnsonoklii/agentgo/apps/agentService/internal/server"
	"github.com/johnsonoklii/agentgo/apps/agentService/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

func wireApp(confServer *conf.Server, data *conf.Data, registry *conf.Registry, logger log.Logger) (*kratos.App, func(), error) {
	dbData, cleanup, err := db.NewData(data, logger)
	if err != nil {
		return nil, nil, err
	}
	agentRepo := db.NewAgentRepo(dbData, logger)
	agentUsecase := agent.NewAgentUsecase(agentRepo, logger)
	agentVersionRepo := db.NewAgentVersionRepo(dbData, logger)
	agentVersionUsecase := agent.NewAgentVersionUsecase(agentRepo, agentVersionRepo, logger)
	agentService := service.NewAgentService(agentUsecase, agentVersionUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, agentService)
	httpServer := server.NewHTTPServer(confServer, agentService)
	registrar := server.NewRegistrar(registry)
	app := newApp(logger, confServer, grpcServer, httpServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
