// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/johnsonoklii/agentgo/apps/agentService/internal/biz"
	"github.com/johnsonoklii/agentgo/apps/agentService/internal/conf"
	"github.com/johnsonoklii/agentgo/apps/agentService/internal/data/repo"
	"github.com/johnsonoklii/agentgo/apps/agentService/internal/server"
	"github.com/johnsonoklii/agentgo/apps/agentService/internal/service"
	"github.com/johnsonoklii/agentgo/pkg/jwt"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

func wireApp(confServer *conf.Server, data *conf.Data, registry *conf.Registry, options *jwt.Options, logger log.Logger) (*kratos.App, func(), error) {
	db := repo.NewDB(data)
	client := repo.NewRedis(data)
	repoData, cleanup, err := repo.NewData(data, logger, db, client)
	if err != nil {
		return nil, nil, err
	}
	agentRepo := repo.NewUserRepo(repoData, logger)
	agentService := service.NewAgentService(agentRepo, logger)
	grpcServer := server.NewGRPCServer(confServer, agentService, logger)
	jwtManager := biz.NewJwtManager(options, logger)
	httpServer := server.NewHTTPServer(confServer, agentService, jwtManager, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
