// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.12.4
// source: agent/v1/agent.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentInfo struct {
	state            protoimpl.MessageState       `protogen:"open.v1"`
	Id               int64                        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description      string                       `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Avatar           string                       `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	SystemPrompt     string                       `protobuf:"bytes,5,opt,name=systemPrompt,proto3" json:"systemPrompt,omitempty"`
	WelcomeMessage   string                       `protobuf:"bytes,6,opt,name=welcomeMessage,proto3" json:"welcomeMessage,omitempty"`
	ToolIds          []string                     `protobuf:"bytes,7,rep,name=toolIds,proto3" json:"toolIds,omitempty"`
	KnowledgeBaseIds []string                     `protobuf:"bytes,8,rep,name=knowledgeBaseIds,proto3" json:"knowledgeBaseIds,omitempty"`
	PublishedVersion string                       `protobuf:"bytes,9,opt,name=publishedVersion,proto3" json:"publishedVersion,omitempty"`
	Enabled          bool                         `protobuf:"varint,10,opt,name=enabled,proto3" json:"enabled,omitempty"`
	UserId           int64                        `protobuf:"varint,11,opt,name=userId,proto3" json:"userId,omitempty"`
	UserName         string                       `protobuf:"bytes,12,opt,name=userName,proto3" json:"userName,omitempty"`
	ToolPresetParams map[string]*ToolPresetParams `protobuf:"bytes,13,rep,name=toolPresetParams,proto3" json:"toolPresetParams,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt        int64                        `protobuf:"varint,14,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt        int64                        `protobuf:"varint,15,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	MultiModel       bool                         `protobuf:"varint,16,opt,name=multiModel,proto3" json:"multiModel,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AgentInfo) Reset() {
	*x = AgentInfo{}
	mi := &file_agent_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfo) ProtoMessage() {}

func (x *AgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfo.ProtoReflect.Descriptor instead.
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AgentInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AgentInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *AgentInfo) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *AgentInfo) GetWelcomeMessage() string {
	if x != nil {
		return x.WelcomeMessage
	}
	return ""
}

func (x *AgentInfo) GetToolIds() []string {
	if x != nil {
		return x.ToolIds
	}
	return nil
}

func (x *AgentInfo) GetKnowledgeBaseIds() []string {
	if x != nil {
		return x.KnowledgeBaseIds
	}
	return nil
}

func (x *AgentInfo) GetPublishedVersion() string {
	if x != nil {
		return x.PublishedVersion
	}
	return ""
}

func (x *AgentInfo) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *AgentInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AgentInfo) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *AgentInfo) GetToolPresetParams() map[string]*ToolPresetParams {
	if x != nil {
		return x.ToolPresetParams
	}
	return nil
}

func (x *AgentInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *AgentInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *AgentInfo) GetMultiModel() bool {
	if x != nil {
		return x.MultiModel
	}
	return false
}

type CreateAgentRequest struct {
	state            protoimpl.MessageState       `protogen:"open.v1"`
	Name             string                       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description      string                       `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Avatar           string                       `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	SystemPrompt     string                       `protobuf:"bytes,4,opt,name=systemPrompt,proto3" json:"systemPrompt,omitempty"`
	WelcomeMessage   string                       `protobuf:"bytes,5,opt,name=welcomeMessage,proto3" json:"welcomeMessage,omitempty"`
	ToolIds          []string                     `protobuf:"bytes,6,rep,name=toolIds,proto3" json:"toolIds,omitempty"`
	KnowledgeBaseIds []string                     `protobuf:"bytes,7,rep,name=knowledgeBaseIds,proto3" json:"knowledgeBaseIds,omitempty"`
	ToolPresetParams map[string]*ToolPresetParams `protobuf:"bytes,8,rep,name=toolPresetParams,proto3" json:"toolPresetParams,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MultiModel       bool                         `protobuf:"varint,9,opt,name=multiModel,proto3" json:"multiModel,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateAgentRequest) Reset() {
	*x = CreateAgentRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAgentRequest) ProtoMessage() {}

func (x *CreateAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAgentRequest.ProtoReflect.Descriptor instead.
func (*CreateAgentRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAgentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAgentRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateAgentRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *CreateAgentRequest) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *CreateAgentRequest) GetWelcomeMessage() string {
	if x != nil {
		return x.WelcomeMessage
	}
	return ""
}

func (x *CreateAgentRequest) GetToolIds() []string {
	if x != nil {
		return x.ToolIds
	}
	return nil
}

func (x *CreateAgentRequest) GetKnowledgeBaseIds() []string {
	if x != nil {
		return x.KnowledgeBaseIds
	}
	return nil
}

func (x *CreateAgentRequest) GetToolPresetParams() map[string]*ToolPresetParams {
	if x != nil {
		return x.ToolPresetParams
	}
	return nil
}

func (x *CreateAgentRequest) GetMultiModel() bool {
	if x != nil {
		return x.MultiModel
	}
	return false
}

type ToolPresetParams struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Tools         map[string]*ToolParamCategory `protobuf:"bytes,1,rep,name=tools,proto3" json:"tools,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // tool_id -> 参数分类
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolPresetParams) Reset() {
	*x = ToolPresetParams{}
	mi := &file_agent_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolPresetParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolPresetParams) ProtoMessage() {}

func (x *ToolPresetParams) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolPresetParams.ProtoReflect.Descriptor instead.
func (*ToolPresetParams) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *ToolPresetParams) GetTools() map[string]*ToolParamCategory {
	if x != nil {
		return x.Tools
	}
	return nil
}

type ToolParamCategory struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Categories    map[string]*ParamValues `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 分类名称 -> 参数值
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolParamCategory) Reset() {
	*x = ToolParamCategory{}
	mi := &file_agent_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolParamCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolParamCategory) ProtoMessage() {}

func (x *ToolParamCategory) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolParamCategory.ProtoReflect.Descriptor instead.
func (*ToolParamCategory) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *ToolParamCategory) GetCategories() map[string]*ParamValues {
	if x != nil {
		return x.Categories
	}
	return nil
}

type ParamValues struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        map[string]string      `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 参数名 -> 参数值
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParamValues) Reset() {
	*x = ParamValues{}
	mi := &file_agent_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParamValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamValues) ProtoMessage() {}

func (x *ParamValues) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamValues.ProtoReflect.Descriptor instead.
func (*ParamValues) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *ParamValues) GetValues() map[string]string {
	if x != nil {
		return x.Values
	}
	return nil
}

type CreateAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *AgentInfo             `protobuf:"bytes,3,opt,name=infrastructure,proto3" json:"infrastructure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAgentResponse) Reset() {
	*x = CreateAgentResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAgentResponse) ProtoMessage() {}

func (x *CreateAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAgentResponse.ProtoReflect.Descriptor instead.
func (*CreateAgentResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *CreateAgentResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateAgentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateAgentResponse) GetData() *AgentInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetAgentListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentListRequest) Reset() {
	*x = GetAgentListRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentListRequest) ProtoMessage() {}

func (x *GetAgentListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentListRequest.ProtoReflect.Descriptor instead.
func (*GetAgentListRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *GetAgentListRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetAgentListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*AgentInfo           `protobuf:"bytes,3,rep,name=infrastructure,proto3" json:"infrastructure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentListResponse) Reset() {
	*x = GetAgentListResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentListResponse) ProtoMessage() {}

func (x *GetAgentListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentListResponse.ProtoReflect.Descriptor instead.
func (*GetAgentListResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *GetAgentListResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetAgentListResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetAgentListResponse) GetData() []*AgentInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       int64                  `protobuf:"varint,1,opt,name=agentId,proto3" json:"agentId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentRequest) Reset() {
	*x = GetAgentRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentRequest) ProtoMessage() {}

func (x *GetAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentRequest.ProtoReflect.Descriptor instead.
func (*GetAgentRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *GetAgentRequest) GetAgentId() int64 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

type GetAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *AgentInfo             `protobuf:"bytes,3,opt,name=infrastructure,proto3" json:"infrastructure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentResponse) Reset() {
	*x = GetAgentResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentResponse) ProtoMessage() {}

func (x *GetAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentResponse.ProtoReflect.Descriptor instead.
func (*GetAgentResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{9}
}

func (x *GetAgentResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetAgentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetAgentResponse) GetData() *AgentInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       int64                  `protobuf:"varint,1,opt,name=agentId,proto3" json:"agentId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAgentRequest) Reset() {
	*x = UpdateAgentRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAgentRequest) ProtoMessage() {}

func (x *UpdateAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAgentRequest.ProtoReflect.Descriptor instead.
func (*UpdateAgentRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateAgentRequest) GetAgentId() int64 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

type UpdateAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *AgentInfo             `protobuf:"bytes,3,opt,name=infrastructure,proto3" json:"infrastructure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAgentResponse) Reset() {
	*x = UpdateAgentResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAgentResponse) ProtoMessage() {}

func (x *UpdateAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAgentResponse.ProtoReflect.Descriptor instead.
func (*UpdateAgentResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateAgentResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdateAgentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateAgentResponse) GetData() *AgentInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeleteAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       int64                  `protobuf:"varint,1,opt,name=agentId,proto3" json:"agentId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAgentRequest) Reset() {
	*x = DeleteAgentRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAgentRequest) ProtoMessage() {}

func (x *DeleteAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAgentRequest.ProtoReflect.Descriptor instead.
func (*DeleteAgentRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteAgentRequest) GetAgentId() int64 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

type DeleteAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAgentResponse) Reset() {
	*x = DeleteAgentResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAgentResponse) ProtoMessage() {}

func (x *DeleteAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAgentResponse.ProtoReflect.Descriptor instead.
func (*DeleteAgentResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteAgentResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DeleteAgentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_agent_v1_agent_proto protoreflect.FileDescriptor

const file_agent_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x14agent/v1/agent.proto\x12\fapi.agent.v1\x1a\x1cgoogle/api/annotations.proto\"\x91\x05\n" +
	"\tAgentInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x12\"\n" +
	"\fsystemPrompt\x18\x05 \x01(\tR\fsystemPrompt\x12&\n" +
	"\x0ewelcomeMessage\x18\x06 \x01(\tR\x0ewelcomeMessage\x12\x18\n" +
	"\atoolIds\x18\a \x03(\tR\atoolIds\x12*\n" +
	"\x10knowledgeBaseIds\x18\b \x03(\tR\x10knowledgeBaseIds\x12*\n" +
	"\x10publishedVersion\x18\t \x01(\tR\x10publishedVersion\x12\x18\n" +
	"\aenabled\x18\n" +
	" \x01(\bR\aenabled\x12\x16\n" +
	"\x06userId\x18\v \x01(\x03R\x06userId\x12\x1a\n" +
	"\buserName\x18\f \x01(\tR\buserName\x12Y\n" +
	"\x10toolPresetParams\x18\r \x03(\v2-.api.agent.v1.AgentInfo.ToolPresetParamsEntryR\x10toolPresetParams\x12\x1c\n" +
	"\tcreatedAt\x18\x0e \x01(\x03R\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x0f \x01(\x03R\tupdatedAt\x12\x1e\n" +
	"\n" +
	"multiModel\x18\x10 \x01(\bR\n" +
	"multiModel\x1ac\n" +
	"\x15ToolPresetParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.api.agent.v1.ToolPresetParamsR\x05value:\x028\x01\"\xdd\x03\n" +
	"\x12CreateAgentRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\"\n" +
	"\fsystemPrompt\x18\x04 \x01(\tR\fsystemPrompt\x12&\n" +
	"\x0ewelcomeMessage\x18\x05 \x01(\tR\x0ewelcomeMessage\x12\x18\n" +
	"\atoolIds\x18\x06 \x03(\tR\atoolIds\x12*\n" +
	"\x10knowledgeBaseIds\x18\a \x03(\tR\x10knowledgeBaseIds\x12b\n" +
	"\x10toolPresetParams\x18\b \x03(\v26.api.agent.v1.CreateAgentRequest.ToolPresetParamsEntryR\x10toolPresetParams\x12\x1e\n" +
	"\n" +
	"multiModel\x18\t \x01(\bR\n" +
	"multiModel\x1ac\n" +
	"\x15ToolPresetParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.api.agent.v1.ToolPresetParamsR\x05value:\x028\x01\"\xae\x01\n" +
	"\x10ToolPresetParams\x12?\n" +
	"\x05tools\x18\x01 \x03(\v2).api.agent.v1.ToolPresetParams.ToolsEntryR\x05tools\x1aY\n" +
	"\n" +
	"ToolsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x125\n" +
	"\x05value\x18\x02 \x01(\v2\x1f.api.agent.v1.ToolParamCategoryR\x05value:\x028\x01\"\xbe\x01\n" +
	"\x11ToolParamCategory\x12O\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2/.api.agent.v1.ToolParamCategory.CategoriesEntryR\n" +
	"categories\x1aX\n" +
	"\x0fCategoriesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.api.agent.v1.ParamValuesR\x05value:\x028\x01\"\x87\x01\n" +
	"\vParamValues\x12=\n" +
	"\x06values\x18\x01 \x03(\v2%.api.agent.v1.ParamValues.ValuesEntryR\x06values\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"p\n" +
	"\x13CreateAgentResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12+\n" +
	"\x04data\x18\x03 \x01(\v2\x17.api.agent.v1.AgentInfoR\x04data\"-\n" +
	"\x13GetAgentListRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\"q\n" +
	"\x14GetAgentListResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12+\n" +
	"\x04data\x18\x03 \x03(\v2\x17.api.agent.v1.AgentInfoR\x04data\"+\n" +
	"\x0fGetAgentRequest\x12\x18\n" +
	"\aagentId\x18\x01 \x01(\x03R\aagentId\"m\n" +
	"\x10GetAgentResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12+\n" +
	"\x04data\x18\x03 \x01(\v2\x17.api.agent.v1.AgentInfoR\x04data\".\n" +
	"\x12UpdateAgentRequest\x12\x18\n" +
	"\aagentId\x18\x01 \x01(\x03R\aagentId\"p\n" +
	"\x13UpdateAgentResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12+\n" +
	"\x04data\x18\x03 \x01(\v2\x17.api.agent.v1.AgentInfoR\x04data\".\n" +
	"\x12DeleteAgentRequest\x12\x18\n" +
	"\aagentId\x18\x01 \x01(\x03R\aagentId\"C\n" +
	"\x13DeleteAgentResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xad\x04\n" +
	"\x05Agent\x12i\n" +
	"\vCreateAgent\x12 .api.agent.v1.CreateAgentRequest\x1a!.api.agent.v1.CreateAgentResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/agents\x12i\n" +
	"\fGetAgentList\x12!.api.agent.v1.GetAgentListRequest\x1a\".api.agent.v1.GetAgentListResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/agents\x12g\n" +
	"\bGetAgent\x12\x1d.api.agent.v1.GetAgentRequest\x1a\x1e.api.agent.v1.GetAgentResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/agents/{agentId}\x12s\n" +
	"\vUpdateAgent\x12 .api.agent.v1.UpdateAgentRequest\x1a!.api.agent.v1.UpdateAgentResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\x1a\x14/v1/agents/{agentId}\x12p\n" +
	"\vDeleteAgent\x12 .api.agent.v1.DeleteAgentRequest\x1a!.api.agent.v1.DeleteAgentResponse\"\x1c\x82\xd3\xe4\x93\x02\x16*\x14/v1/agents/{agentId}B\x1eZ\x1cagentService/api/agent/v1;v1b\x06proto3"

var (
	file_agent_v1_agent_proto_rawDescOnce sync.Once
	file_agent_v1_agent_proto_rawDescData []byte
)

func file_agent_v1_agent_proto_rawDescGZIP() []byte {
	file_agent_v1_agent_proto_rawDescOnce.Do(func() {
		file_agent_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_v1_agent_proto_rawDesc), len(file_agent_v1_agent_proto_rawDesc)))
	})
	return file_agent_v1_agent_proto_rawDescData
}

var file_agent_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_agent_v1_agent_proto_goTypes = []any{
	(*AgentInfo)(nil),            // 0: api.agent.v1.AgentInfo
	(*CreateAgentRequest)(nil),   // 1: api.agent.v1.CreateAgentRequest
	(*ToolPresetParams)(nil),     // 2: api.agent.v1.ToolPresetParams
	(*ToolParamCategory)(nil),    // 3: api.agent.v1.ToolParamCategory
	(*ParamValues)(nil),          // 4: api.agent.v1.ParamValues
	(*CreateAgentResponse)(nil),  // 5: api.agent.v1.CreateAgentResponse
	(*GetAgentListRequest)(nil),  // 6: api.agent.v1.GetAgentListRequest
	(*GetAgentListResponse)(nil), // 7: api.agent.v1.GetAgentListResponse
	(*GetAgentRequest)(nil),      // 8: api.agent.v1.GetAgentRequest
	(*GetAgentResponse)(nil),     // 9: api.agent.v1.GetAgentResponse
	(*UpdateAgentRequest)(nil),   // 10: api.agent.v1.UpdateAgentRequest
	(*UpdateAgentResponse)(nil),  // 11: api.agent.v1.UpdateAgentResponse
	(*DeleteAgentRequest)(nil),   // 12: api.agent.v1.DeleteAgentRequest
	(*DeleteAgentResponse)(nil),  // 13: api.agent.v1.DeleteAgentResponse
	nil,                          // 14: api.agent.v1.AgentInfo.ToolPresetParamsEntry
	nil,                          // 15: api.agent.v1.CreateAgentRequest.ToolPresetParamsEntry
	nil,                          // 16: api.agent.v1.ToolPresetParams.ToolsEntry
	nil,                          // 17: api.agent.v1.ToolParamCategory.CategoriesEntry
	nil,                          // 18: api.agent.v1.ParamValues.ValuesEntry
}
var file_agent_v1_agent_proto_depIdxs = []int32{
	14, // 0: api.agent.v1.AgentInfo.toolPresetParams:type_name -> api.agent.v1.AgentInfo.ToolPresetParamsEntry
	15, // 1: api.agent.v1.CreateAgentRequest.toolPresetParams:type_name -> api.agent.v1.CreateAgentRequest.ToolPresetParamsEntry
	16, // 2: api.agent.v1.ToolPresetParams.tools:type_name -> api.agent.v1.ToolPresetParams.ToolsEntry
	17, // 3: api.agent.v1.ToolParamCategory.categories:type_name -> api.agent.v1.ToolParamCategory.CategoriesEntry
	18, // 4: api.agent.v1.ParamValues.values:type_name -> api.agent.v1.ParamValues.ValuesEntry
	0,  // 5: api.agent.v1.CreateAgentResponse.infrastructure:type_name -> api.agent.v1.AgentInfo
	0,  // 6: api.agent.v1.GetAgentListResponse.infrastructure:type_name -> api.agent.v1.AgentInfo
	0,  // 7: api.agent.v1.GetAgentResponse.infrastructure:type_name -> api.agent.v1.AgentInfo
	0,  // 8: api.agent.v1.UpdateAgentResponse.infrastructure:type_name -> api.agent.v1.AgentInfo
	2,  // 9: api.agent.v1.AgentInfo.ToolPresetParamsEntry.value:type_name -> api.agent.v1.ToolPresetParams
	2,  // 10: api.agent.v1.CreateAgentRequest.ToolPresetParamsEntry.value:type_name -> api.agent.v1.ToolPresetParams
	3,  // 11: api.agent.v1.ToolPresetParams.ToolsEntry.value:type_name -> api.agent.v1.ToolParamCategory
	4,  // 12: api.agent.v1.ToolParamCategory.CategoriesEntry.value:type_name -> api.agent.v1.ParamValues
	1,  // 13: api.agent.v1.Agent.CreateAgent:input_type -> api.agent.v1.CreateAgentRequest
	6,  // 14: api.agent.v1.Agent.GetAgentList:input_type -> api.agent.v1.GetAgentListRequest
	8,  // 15: api.agent.v1.Agent.GetAgent:input_type -> api.agent.v1.GetAgentRequest
	10, // 16: api.agent.v1.Agent.UpdateAgent:input_type -> api.agent.v1.UpdateAgentRequest
	12, // 17: api.agent.v1.Agent.DeleteAgent:input_type -> api.agent.v1.DeleteAgentRequest
	5,  // 18: api.agent.v1.Agent.CreateAgent:output_type -> api.agent.v1.CreateAgentResponse
	7,  // 19: api.agent.v1.Agent.GetAgentList:output_type -> api.agent.v1.GetAgentListResponse
	9,  // 20: api.agent.v1.Agent.GetAgent:output_type -> api.agent.v1.GetAgentResponse
	11, // 21: api.agent.v1.Agent.UpdateAgent:output_type -> api.agent.v1.UpdateAgentResponse
	13, // 22: api.agent.v1.Agent.DeleteAgent:output_type -> api.agent.v1.DeleteAgentResponse
	18, // [18:23] is the sub-list for method output_type
	13, // [13:18] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_agent_v1_agent_proto_init() }
func file_agent_v1_agent_proto_init() {
	if File_agent_v1_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_v1_agent_proto_rawDesc), len(file_agent_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_v1_agent_proto_goTypes,
		DependencyIndexes: file_agent_v1_agent_proto_depIdxs,
		MessageInfos:      file_agent_v1_agent_proto_msgTypes,
	}.Build()
	File_agent_v1_agent_proto = out.File
	file_agent_v1_agent_proto_goTypes = nil
	file_agent_v1_agent_proto_depIdxs = nil
}
